# Generated by Django 5.2.4 on 2025-08-03 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Analysis', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_query', models.TextField(blank=True, null=True)),
                ('agent_explanation', models.TextField(blank=True, null=True)),
                ('agent_workflow_plan', models.JSONField(blank=True, null=True)),
                ('user_edited_workflow_plan', models.JSONField(blank=True, null=True)),
                ('execution_log', models.JSONField(blank=True, null=True)),
                ('final_map_result', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_app.analysisthread')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
