# Generated by Django 5.2.4 on 2025-08-04 02:15

import agent_app.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="A user-friendly name for the layer, e.g., 'Project Boundary'", max_length=100)),
                ('file', models.FileField(upload_to=agent_app.models.get_upload_path)),
                ('data_type', models.CharField(choices=[('vector', 'Vector'), ('raster', 'Raster')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_layers', to='agent_app.analysisthread')),
            ],
        ),
    ]
