# Generated by Django 5.2.4 on 2025-08-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0002_userdatalayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdatalayer',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='userdatalayer',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='userdatalayer',
            name='data_type',
            field=models.CharField(choices=[('vector', 'Vector'), ('raster', 'Raster')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdatalayer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
