# Generated by Django 5.2.4 on 2025-08-08 04:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0003_alter_userdatalayer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisROI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geometry', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roi', to='agent_app.analysisthread')),
            ],
        ),
    ]
